//<script type="text/javascript">

Pman.Readers.Pressrelease_entry = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		{name : 'client_id',type : 'int'},
		'language',
		{name : 'publish_dt',type : 'date',dateFormat : 'Y-m-d'},
		{name : 'publish_dt_tz',type : 'int'},
		'headline',
		'content',
		'content_data',
		'content_links',
		{name : 'updated',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		{name : 'created',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		{name : 'created_by',type : 'int'},
		{name : 'updated_by',type : 'int'},
		{name : 'owner_id',type : 'int'},
		{name : 'publish_status',type : 'int'},
		{name : 'client_id_id',type : 'int'},
		{name : 'client_id_office_id',type : 'int'},
		'client_id_name',
		'client_id_phone',
		'client_id_fax',
		'client_id_email',
		{name : 'client_id_company_id',type : 'int'},
		'client_id_role',
		{name : 'client_id_active',type : 'int'},
		'client_id_remarks',
		'client_id_passwd',
		{name : 'client_id_owner_id',type : 'int'},
		'client_id_lang',
		{name : 'client_id_no_reset_sent',type : 'int'},
		'client_id_action_type',
		{name : 'client_id_project_id',type : 'int'},
		{name : 'created_by_id',type : 'int'},
		{name : 'created_by_office_id',type : 'int'},
		'created_by_name',
		'created_by_phone',
		'created_by_fax',
		'created_by_email',
		{name : 'created_by_company_id',type : 'int'},
		'created_by_role',
		{name : 'created_by_active',type : 'int'},
		'created_by_remarks',
		'created_by_passwd',
		{name : 'created_by_owner_id',type : 'int'},
		'created_by_lang',
		{name : 'created_by_no_reset_sent',type : 'int'},
		'created_by_action_type',
		{name : 'created_by_project_id',type : 'int'},
		{name : 'updated_by_id',type : 'int'},
		{name : 'updated_by_office_id',type : 'int'},
		'updated_by_name',
		'updated_by_phone',
		'updated_by_fax',
		'updated_by_email',
		{name : 'updated_by_company_id',type : 'int'},
		'updated_by_role',
		{name : 'updated_by_active',type : 'int'},
		'updated_by_remarks',
		'updated_by_passwd',
		{name : 'updated_by_owner_id',type : 'int'},
		'updated_by_lang',
		{name : 'updated_by_no_reset_sent',type : 'int'},
		'updated_by_action_type',
		{name : 'updated_by_project_id',type : 'int'},
		{name : 'owner_id_id',type : 'int'},
		{name : 'owner_id_office_id',type : 'int'},
		'owner_id_name',
		'owner_id_phone',
		'owner_id_fax',
		'owner_id_email',
		{name : 'owner_id_company_id',type : 'int'},
		'owner_id_role',
		{name : 'owner_id_active',type : 'int'},
		'owner_id_remarks',
		'owner_id_passwd',
		{name : 'owner_id_owner_id',type : 'int'},
		'owner_id_lang',
		{name : 'owner_id_no_reset_sent',type : 'int'},
		'owner_id_action_type',
		{name : 'owner_id_project_id',type : 'int'}
	]
};

Pman.Readers.Pressrelease_entry_related = {
	root : 'data',
	totalProperty : 'total',
	id : 'id',
	xtype : 'JsonReader',
	fields : [
		{name : 'id',type : 'int'},
		{name : 'entry_id',type : 'int'},
		'relationship',
		'table_name',
		{name : 'table_id',type : 'int'},
		{name : 'entry_id_id',type : 'int'},
		{name : 'entry_id_client_id',type : 'int'},
		'entry_id_language',
		{name : 'entry_id_publish_dt',type : 'date',dateFormat : 'Y-m-d'},
		{name : 'entry_id_publish_dt_tz',type : 'int'},
		'entry_id_headline',
		'entry_id_content',
		'entry_id_content_data',
		'entry_id_content_links',
		{name : 'entry_id_updated',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		{name : 'entry_id_created',type : 'date',dateFormat : 'Y-m-d H:i:s'},
		{name : 'entry_id_created_by',type : 'int'},
		{name : 'entry_id_updated_by',type : 'int'},
		{name : 'entry_id_owner_id',type : 'int'},
		{name : 'entry_id_publish_status',type : 'int'}
	]
};
